module.exports = {

    CONSTANTS: {
        // *** ALGUNOS CÓDIGOS DE ERROR CON LA BD ***
        PROTOCOL_CONNECTION_LOST: 'PROTOCOL_CONNECTION_LOST',
        ER_CON_COUNT_ERROR: 'ER_CON_COUNT_ERROR',
        ECONNREFUSED: 'ECONNREFUSED',
        ER_ACCESS_DENIED_ERROR: 'ER_ACCESS_DENIED_ERROR'
        
        // ER_ACCESS_DENIED_ERROR: 'ER_ACCESS_DENIED_ERROR',
        // ER_BAD_DB_ERROR: 'ER_BAD_DB_ERROR',
        //ER_DBACCESS_DENIED_ERROR: 'ER_DBACCESS_DENIED_ERROR'

        // *** FIN BLOQUE CÓDIGOS BD ***
    }
  };
  